server:
 port: 9005

spring:
 application:
  name: API-Gateway
 cloud:
  gateway:
   routes:
    - id: employeeService
      uri: lb://employee-service
      predicates:
       - Path=/api/employees/**
    - id: departmentService
      uri: lb://departmentservice
      predicates:
       - Path=/api/departments/**
#dev tools dependency will not like this file. it will not read this file with dev
#URI: Important!!!
#URI need to match with name shown on server. Case does not matter
#Predicate: Important!!, wont be able to find the links without it